### ISSUE TITLE
Incorrect autocomplete suggestions for hyphenated class names.

### ISSUE THREAD

**Issue by jasonplatts** [jasonplatts/tailwindcss-nova-ext#1]
When the user types a class name containing a hyphen, the autocomplete suggestions stop when the user gets to a hyphen. It then continues again once the user has typed past that hypen, but the suggestions are no longer the most relevant because anything preceding the hyphen is ignored.

**Comment by jasonplatts** [comment]
The extension currently adds completion items using the JavaScript API https://docs.nova.app/api-reference/completion-item/. It's possible that the better solution may be to use an xml file for generating completion items, but I have not yet been able to generate a completion item this way. The Panic docs discuss this at https://docs.nova.app/syntax-reference/completions/.

**Comment by jasonplatts** [comment]
I have an email into Panic asking if they have any suggestions. Will add any information they might send.

**Comment by jasonplatts** [comment]
After talking to some devs on the Nova Extension Discord channel, the consensus seems to be that it is not currently possible to change the user entered text evaluated for completions when using the JavaScript API. As it stands, Nova considers the word boundary (with no hyphens) to be the evaluated user text. This issue will likely need to be addresses on the Nova side.

**Comment by jasonplatts** [comment]
> The extension currently adds completion items using the JavaScript API https://docs.nova.app/api-reference/completion-item/. It's possible that the better solution may be to use an xml file for generating completion items, but I have not yet been able to generate a completion item this way. The Panic docs discuss this at https://docs.nova.app/syntax-reference/completions/.

I have discovered that the xml method of providing completions also has some limitations. It does not appear to offer the ability to include details, documentation, or color symbols. Still waiting on a response from Panic to determine a best way forward.

**Comment by jasonplatts** [comment]
Quick update. I am in contact with Panic and working through this issue.

**Comment by jasonplatts** [comment]
It has been determined that this issue will need to be resolved in Nova and will be addressed in Nova 1.3.

**Comment by jasonplatts** [comment]
This issue should now be fixed in Nova 2.0.

**Comment by chipotle** [comment]
Weird question: this doesn't seem work in Blade templates (if you start typing, e.g., `bg-blue-500`, then the autocompletion stops when you type the first hyphen). I see Blade is listed in the extension configuration as a supported file type; is there something that could be happening in the Blade extension that's borking this up somehow? It looks like it has a simple XML file for completion and I'm not seeing anything obvious there, but my knowledge of Nova extensions is pretty limited.
