### ISSUE TITLE
support completions in .css or .scss files

### ISSUE THREAD

**Issue by cmdillon** [jasonplatts/tailwindcss-nova-ext#12]
hi! first of great project. i have one feature request: support completions in .css or .scss files. at the moment this seems not to work, emmit seems to only work in those file types.

**Comment by jasonplatts** [comment]
Hi @cmdillon. Thanks. Glad to hear you are finding it useful.

Yes, despite being enabled for these file types, Nova does not support class completions in .css or .scss files. I hope to have this fixed in a future update and will check in with Panic to see what might be possible.

Thanks again!

**Comment by joshwalsh** [comment]
Just raising my hand as someone who would also love this feature!

Thanks for all you do.

**Comment by jasonplatts** [comment]
Thanks @joshwalsh!

**Comment by jasonplatts** [comment]
@joshwalsh, @cmdillon, autocomplete suggestions should now be offered in these files. Please let me know if you continue to have issues.

Thanks!
