### ISSUE TITLE
Extension encountered an uncaught exception

### ISSUE THREAD

**Issue by dedostorpes** [jasonplatts/tailwindcss-nova-ext#17]
First of all, thanks for making the extension.

Up to v2.2, the extension used to work perfectly.

Now I decided to update it to Version 3.0.3 and it doesn't work at all.

`Extension encountered an uncaught exception:
/Users/Master/Library/Application Support/Nova/Extensions/jasonplatts.tailwindcss/Scripts/completion_provider.js (Line 57, Column 0)
SyntaxError: Unexpected token '.'
    [native code]
    file:///Users/Master/Library/Application%20Support/Nova/Extensions/jasonplatts.tailwindcss/Scripts/main.js:5:40`

Also, when I click the cloud icon next to "Tailwind CSS (v2.2.4)" in the sidebar, I get this pop-up error message: 

`No command found with the name “tailwind.openDocs”.
Check to make sure the extension for the command is installed and up to date.
`

I made a clean Nova reinstall but the issue persists.

I have Nova 7.2 installed.
Mojave 10.14.6

**Comment by jasonplatts** [comment]
Hi @dedostorpes. Thanks for letting me know!

Could you please try uninstalling and reinstalling the extension? And then perhaps close then reopen Nova.

**Comment by dedostorpes** [comment]
> Hi @dedostorpes. Thanks for letting me know!
> 
> Could you please try uninstalling and reinstalling the extension? And then perhaps close then reopen Nova.

Hi, yes, I already did that.

1. Reinstalled Nova (made a clean install; deleting all preferences).
2. Reinstalled extension.
3. Disabled every other extension.
4. I downloaded all releases from here (2.2 to 3.0.3) and I'm getting the same error with every release, except v2.2 which is the only one that works.
5. I also restarted the Mac, just in case.

I have no clue. I never experienced issues with other extensions.

**Comment by jasonplatts** [comment]
I have a feeling it may be related to newer JavaScript syntax. I have included a beta 3.0.4 version below, if you would like to try it. If this fixes the issue, I can release a new version with the fix.

To install it, just uninstall the current version you have and double click on the unzipped file below.

[tailwindcss.novaextension.zip](https://github.com/jasonplatts/tailwindcss-nova-ext/files/6950911/tailwindcss.novaextension.zip)

**Comment by dedostorpes** [comment]
Indeed, that fixed it!

Thanks a lot for your help @jasonplatts !

**Comment by jasonplatts** [comment]
Great!

You are most welcome @dedostorpes. Thanks for letting me know about the issue!

**Comment by jasonplatts** [comment]
Fixed in version 3.0.4.
