### ISSUE TITLE
Extension attempts to autocomplete in strings that aren't classes

### ISSUE THREAD

**Issue by michaelflores-italic** [jasonplatts/tailwindcss-nova-ext#18]
I noticed that I was getting Tailwind autocomplete suggestions when typing code comments in TSX files. I filed an Issue with Nova but they pointed me to the extension so I am filing it here. This should be reproducible in any TSX or likely JSX file, but I can include a sample here if it proves difficult to repro.

**Comment by jasonplatts** [comment]
Thanks for letting me know Michael. Yes, unfortunately, the current version of the extension does not do a great job of preventing suggestions in these types of situations. Improved suggestions are on the roadmap.

**Comment by jasonplatts** [comment]
Hi @michaelflores-italic. Version 4.1 improves autocompletion suggestions. Please let me know if you continue to have any issues in TSX or JSX files.

Thanks!

**Comment by jasonplatts** [comment]
I'm going to assume this problem is resolved, so will close this issue. If any problems remain, please feel free to open another issue.

**Comment by alex-ketch** [comment]
Hi @jasonplatts, unfortunately I'm facing this issue with the latest release.
The extension populates list of suggestions for all fields, not just `className`

Can be tested with a simple TSX file:

```tsx
import React from 'react'

export const Test = () => {
  return <input type="" />
}
```

_Cursor was located in the `type` attribute value_
![Screenshot 2022-03-15 at 16 39 31](https://user-images.githubusercontent.com/1646307/158468563-af936d3d-f022-4161-852e-e85be5d1628a.png)

Let me know if you need any more info, or feel free to point me in the general direction of where a fix would need to happen and can poke around :)

Thanks!

**Comment by alex-ketch** [comment]
Sorry for not getting back to you sooner @jasonplatts, I only ever had a partial solution and was hoping for an epiphany for a workaround.
I've [filed a feature request](https://devforum.nova.app/t/expose-attribute-details-in-completioncontext/1743) in the Nova forum, but in case anyone is curious for a rough patch, I've modified the [`completion_provider.js#121`](https://github.com/jasonplatts/tailwindcss-nova-ext/blob/74042e8d931994846b1d5f60f9d64dc568986ed2/Scripts/completion_provider.js#L121) as such:


```diff
// Allow completions if context selectors is a HTML class attribute value.
- if (context.selectors[0].matches('html.tag.attribute.class.value.double-quoted')) { return false }
+ if (
+   context.selectors[0].matches('tsx.value') ||
+   // Allow completions if context selectors is a HTML class attribute value.
+   context.selectors[0].matches('html.tag.attribute.class.value.double-quoted') ||
+   // Allow completions in other files if contained within single quotes or double quotes.
+   // This, for example, enables completions in Rails ERB files when passing a class option to the link_to method.
+   context.selectors[0].classes.includes('single-quoted') ||
+   context.selectors[0].classes.includes('double-quoted')
+ ) { 
+   const classNameRegExp = new RegExp(/=(\w+)/, 'g')
+   let tagName = context.line.trimStart().trim().split('').reverse().join('')
+   tagName = classNameRegExp.exec(tagName)[1].split('').reverse().join('')
+ 
+   return !(tagName || '').startsWith('class')
+ }

if (context.selectors[0].matches('css')) { return false }

```

**Comment by EmranMR** [comment]
> Sorry for not getting back to you sooner @jasonplatts, I only ever had a partial solution and was hoping for an epiphany for a workaround. I've [filed a feature request](https://devforum.nova.app/t/expose-attribute-details-in-completioncontext/1743) in the Nova forum, but in case anyone is curious for a rough patch, I've modified the [`completion_provider.js#121`](https://github.com/jasonplatts/tailwindcss-nova-ext/blob/74042e8d931994846b1d5f60f9d64dc568986ed2/Scripts/completion_provider.js#L121) as such:
> 


@alex-ketch There is a command that allows you to turn off tailwind suggestions on the fly. Just open up the **_command palette_** and press `tt` or type `Toggle TailwindCSS`. It is handy when coding outside of template files. I remember discussing this with Jason when I submitted a pull request similar to yours. [#24](https://github.com/jasonplatts/tailwindcss-nova-ext/pull/24) Unfortunately so many frameworks and templates that it makes it impossible to keep up with. Not sure if the new tree-sitter parser is any better, allowing us cherry picking `context` more appropriately?
