### ISSUE TITLE
Tailwind configuration file not found

### ISSUE THREAD

**Issue by splurtcake** [jasonplatts/tailwindcss-nova-ext#19]
Hello,

I have a tailwind.config.js file in the root of my project, but the extension is not finding this file resulting in a pop message message saying to change the path of the config file.

The problem is that I have no idea where to do that and the documentation of extension is not obvious.

If I go to Preferences > Workspace as suggested in the README, I see a completely different view to what is described in your screenshot. Where can I find this screen in Nova?

![Screen Shot 2021-10-08 at 9 43 08 am](https://user-images.githubusercontent.com/7219867/136472289-289d6a1f-61f8-42ce-b79c-dc9461246471.png)

My workspace preferences look like this

![Screen Shot 2021-10-08 at 9 45 10 am](https://user-images.githubusercontent.com/7219867/136472356-24ba3748-2953-4171-a5a4-3932bcce33f8.png)

Cheers!

**Comment by jasonplatts** [comment]
Hi.

Are you working on a remote project by chance? If so, the extension isn’t able to search the project directory for the tailwind.config.js file. In these cases, Nova also does not provide workspace settings.

If you are accessing a remote project, unfortunately, the only workaround is to move the project to a local directory.

Hope this helps!

Jason

**Comment by jasonplatts** [comment]
I'm not sure if you figured this out or decided not to use the extension for your project. Either way, I think I misunderstood the problem. You need to access your project settings, not workspace, which can be done by going to the "Project" menu and selecting "Project Settings…".

However, as previously mentioned, this will not be possible if the project is remote.

Jason
