### ISSUE TITLE
Autocompletion in php files

### ISSUE THREAD

**Issue by KirillDakhnyuk** [jasonplatts/tailwindcss-nova-ext#20]
Hi, 

Unfortunately autocomplete works not only in html, blade, etc. files but it's also suggesting styles in php files :(

**Comment by jasonplatts** [comment]
Hi @KirillDakhnyuk. Thanks for letting me know. Unfortunately, Tailwind suggestions are not perfect at the moment. Hope to get this addressed in a future update. The problem you are experiencing is along the same lines as issue #18.

**Comment by KirillDakhnyuk** [comment]
@jasonplatts thank you.

**Comment by jasonplatts** [comment]
@KirillDakhnyuk autocomplete suggestions have been improved in version 4.1. Please let me know if you continue to notice issues.
