### ISSUE TITLE
Support everything new in Tailwind 3.0

### ISSUE THREAD

**Issue by mattjis** [jasonplatts/tailwindcss-nova-ext#21]
https://tailwindcss.com/blog/tailwindcss-v3

**Comment by gobijan** [comment]
Is there a diff can one easily update it?

**Comment by jasonplatts** [comment]
Hi. Thanks the feedback. Hoping to add version 3 support soon.

@gobijan, PRs are always welcome. If you download the latest main branch, you will find some classes have already been updated for v3.0.0. These are in the "Definitions/3.0.0" folder. I use the Tailwind docs at, https://tailwindcss.com/docs, as closely as possible to define the structure of these files. The latest commits should provide some examples of my current update process. If you wish to contribute and have any questions, please let me know.

**Comment by gobijan** [comment]
I had a look at the tailwindcss-intellisense package for vscode and how they do it and found that they developed an LSP for this. It is currently nested in the project (not a separate repo as one might suggest):

https://github.com/tailwindlabs/tailwindcss-intellisense/tree/master/packages/tailwindcss-language-server

Further they also provide a tailwindcss language service:
https://github.com/tailwindlabs/tailwindcss-intellisense/tree/master/packages/tailwindcss-language-service

It could make sense to evaluate this option so the extension for nova wouldnt need to reimplement the definitions based on the documentation.

Have you seen this? Would it make sense to you?

Cheers

**Comment by jasonplatts** [comment]
Thanks @gobijan. This is definitely something I have considered and it does make complete sense. I was hoping to get some user input on this along the way. I'm going to create a new issue so that this discussion might get more attention.

**Comment by jasonplatts** [comment]
This has been added in v4.0.
