### ISSUE TITLE
Converting extension to use a language server?

### ISSUE THREAD

**Issue by jasonplatts** [jasonplatts/tailwindcss-nova-ext#22]
I had a look at the tailwindcss-intellisense package for vscode and how they do it and found that they developed an LSP for this. It is currently nested in the project (not a separate repo as one might suggest):

https://github.com/tailwindlabs/tailwindcss-intellisense/tree/master/packages/tailwindcss-language-server

Further they also provide a tailwindcss language service:
https://github.com/tailwindlabs/tailwindcss-intellisense/tree/master/packages/tailwindcss-language-service

It could make sense to evaluate this option so the extension for nova wouldnt need to reimplement the definitions based on the documentation.

Have you seen this? Would it make sense to you?

Cheers

_Originally posted by @gobijan in https://github.com/jasonplatts/tailwindcss-nova-ext/issues/21#issuecomment-993622586_

**Comment by jasonplatts** [comment]
The above suggestion was made by @gobijan.

This previous issue I posted gives some idea of my thought process and why I haven't yet gone that direction, https://github.com/jasonplatts/tailwindcss-nova-ext/issues/2.

However, I am completely open to looking at again and would love some input. There are some obvious benefits.

**Comment by jasonplatts** [comment]
As an aside, I would like to add additional features, but there is a lot of work involved in this extension. Unfortunately, I don't have as much time to spend on it as I would like.

If anyone is interested in contributing, please do. PRs are always welcome. I would also be open to adding some maintainers if someone wants to become more involved.

**Comment by gobijan** [comment]
Hey @jasonplatts,

I have a few vacation days now. In case I can cook something up I'll get back to you. I just can't promise anything at the moment :)

I read the older issue you created. One quick question: so one needs a full tailwind installation to get it going?

Cheers
Bijan

**Comment by jasonplatts** [comment]
No worries. If there is anything I can do to help, just let me know.

It's been a while since I looked, but last I knew the Tailwind VS Code extension required a full installation of Tailwind. I don't think that's changed.

**Comment by jasonplatts** [comment]
Does anyone find the extension's sidebar documentation useful as a reference?

**Comment by gobijan** [comment]
I do :) Love it!

**Comment by jasonplatts** [comment]
Thanks! Great to know that others find it helpful.

It would be really nice if the Tailwind documentation was available as an API. Also, if Nova provided a way of searching and filtering sidebar items. I requested that feature be added to the Nova extension API, but Panic hasn't included it yet. Hopefully it's on the way.

**Comment by jasonplatts** [comment]
It has occurred to me that there may be another issue with handling the Nova extension the same way as the VS Code extension. Some projects using frameworks, such as Ruby on Rails (tailwindcss-rails gem), are now using the Tailwind executable instead of the typical Tailwind Node.js installation method. There is some information about it here, https://tailwindcss.com/blog/standalone-cli.

Maybe it is possible to implement the Nova extension in a way that makes use of the new Tailwind executable?
