### ISSUE TITLE
Detects additional tailwind.config.js file as part of @tailwindcss/forms within node_modules

### ISSUE THREAD

**Issue by chrisgrande** [jasonplatts/tailwindcss-nova-ext#25]
A `tailwind.config.js` is installed as part of [@tailwindcss/forms](https://github.com/tailwindlabs/tailwindcss-forms) — the extension detects this causing it to think there are two config files in the project.

<img width="319" alt="Multiple Tailwind Configs" src="https://user-images.githubusercontent.com/825577/152418867-6f5ac8ad-86df-43de-978c-029e0d0aaf1d.png">

**Comment by jasonplatts** [comment]
Thanks, @chrisgrande. I'll work on getting this fixed.

**Comment by jasonplatts** [comment]
@chrisgrande, this issue should now be fixed in v4.2.2. Thanks again!

**Comment by chrisgrande** [comment]
Awesome — thank you!
