### ISSUE TITLE
Autocompletion only works in HTML files

### ISSUE THREAD

**Issue by jasonplatts** [jasonplatts/tailwindcss-nova-ext#3]
Autocompletion should work correctly in other files, including:

- erb
- php

**Comment by jasonplatts** [comment]
I am communicating with Panic on this issue.

**Comment by florianbouvot** [comment]
@jasonplatts is there a way to have autocompletion in `.html.twig` files?

**Comment by jasonplatts** [comment]
Hi @florianbouvot. Thanks for asking about support for Twig files. Other users have also asked about support for other file types, so I plan to add the ability for users to set these in preferences in the next release.
