### ISSUE TITLE
Tailwind Completion stopped working with Nova 10

### ISSUE THREAD

**Issue by mccousin** [jasonplatts/tailwindcss-nova-ext#32]
Is it only me or did the completion stop with Panic Nova 10. Can't get it to work.
I am on MacOS 13.0, enabled only tailwindcss Extension, opened a new html-File and tried to aplly tailwind-classes to a html-Tag.
No suggestions appear.
Any hints?

**Comment by BryanSchuetz** [comment]
not only you

**Comment by oliwoodsuk** [comment]
Yeah, same. I'm new to the extension, so it's also possible I haven't set it up correctly.

**Comment by jasonplatts** [comment]
Hi everyone. Thanks for bringing this to my attention. There is an issue with the extension and Nova 10. There will be a fix shortly.

**Comment by jasonplatts** [comment]
This issue should be fixed as of extension version 4.4. Thanks everyone! Please let me know if anyone continues to have issues with completions.
