### ISSUE TITLE
Tailwind completions will not work on .jsx files with the `JavaScript` syntax type in Nova 10

### ISSUE THREAD

**Issue by guillermo-avalos** [jasonplatts/tailwindcss-nova-ext#33]
Ever since Panic removed the JSX syntax styling from Nova 10, the extension will no longer offer completions. It will work if the file extension is changed to `.tsx` or if the TSX syntax is chosen for `.js` or `.jsx` files.

**Comment by jasonplatts** [comment]
I just pushed an update that should hopefully fix this issue. Please let me know if the problem continues.

**Comment by jasonplatts** [comment]
Great! No worries. Thanks for letting me know.
