### ISSUE TITLE
The extension “Tailwind CSS” has stopped responding.

### ISSUE THREAD

**Issue by yabdab** [jasonplatts/tailwindcss-nova-ext#7]
Getting this error on a regular basis ...

https://p112.p2.n0.cdn.getcloudapp.com/items/6quPzmzq/Image%202020-10-22%20at%202.51.41%20PM.png?v=3b36853573c976d028860f7170aed005

Is there a log to show what the issue could be?

Using macOS 10.15.6 and latest Nova build.

**Comment by jasonplatts** [comment]
Thanks yabdab. Not certain, but I think this might have been introduced in the 2.0 update. Looking at the problem and am in touch with Panic to see if they have any ideas.

I think I have discovered what scenario causes the issue and that is when the user types the first and only class name of the HTML element. Are you able to verify this too? Also what file type are you using when this occurs?

**Comment by yabdab** [comment]
@jasonplatts I mainly work on *.php and ..blade.php files (PHP-HTML)

**Comment by mattgossman** [comment]
I was experiencing the same error prior to the 2.0 update.

**Comment by jasonplatts** [comment]
Thanks @mattgossman for letting me know. I am doing some debugging now.

**Comment by jasonplatts** [comment]
Thanks @yabdab and @mattgossman for reporting this bug. I have found the issue and will release an update shortly to fix the bug.
